# ==========================================
# 공통 설정 (기본값)
# ==========================================
server:
  port: 8080
spring:
  profiles:
    active: dev # 기본 실행 프로필 (Render 배포 시 prod 적용)
  datasource:
    url: jdbc:postgresql://localhost:5432/buskerspot
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: buskerspot0803@gmail.com
    password: lnuukcffijpkuayo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: ${JWT_SECRET:everystay_1592_band_bumsu_9027_secure_key}
  expiration: 86400000
api:
  groq:
    key: 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
  kakao:
    rest-key: 1288a46c1221b166bc863a8c66516afe
    client-secret: ovvR9Fo8StMuxeBIKk0ZbAy3jBeCxipS
    redirect-uri: http://localhost:3000/oauth/kakao/callback
  google:
    client-id: 837963657825-gejm31g6via3o16dciknj0l70ss2sinu.apps.googleusercontent.com
    client-secret: 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
    redirect-uri: http://localhost:3000/oauth/google/callback
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
---
# ==========================================
# 개발용 환경 (dev 프로필)
# ==========================================
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/buskerspot_dev
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
---
# ==========================================
# 배포용 환경 (prod 프로필 - Render)
# ==========================================
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
jwt:
  secret: ${JWT_SECRET}
