server:
  port: 8080 # Node.js와 동일하게 5000번 포트 사용

spring:
  datasource:
    url: postgresql://buskerspot_db_user:E2i6NDW244OTaYJ2odcnJxsKjIkFTCEM@dpg-d9uku16417fc738finog-a/buskerspot_db
    username: ${DB_USERNAME:buskerspot_db_user}
    password: ${DB_PASSWORD:E2i6NDW244OTaYJ2odcnJxsKjIkFTCEM}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # 테이블 자동 생성/수정 옵션 (none, update, create 등 선택 가능)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: buskerspot0803@gmail.com
    password: lnuukcffijpkuayo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET:clock_cat_1241_miles_runaway_0821_icepack_2023_imago_flower_protein_jspark_dejavu_2251_rokarmy__lucasdigne}
  expiration: 86400000 # 토큰 유효 기간 (24시간, 밀리초 단위)

api:
  groq:
    key: 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
  kakao:
    rest-key: 1288a46c1221b166bc863a8c66516afe
    client-secret: ovvR9Fo8StMuxeBIKk0ZbAy3jBeCxipS
    redirect-uri: http://localhost:3000/oauth/kakao/callback

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE